name: Version Increment

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  version-increment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: git config user.email "quddusnuriman@gmail.com"
      - run: git config user.name "nrmnqdds"
      - run: npm version minor -m "v%s"
      - run: VERSION=$(node -p "require('./package.json').version")
      - run: git tag ${VERSION}
      - run: git push "https://$GITHUB_ACTOR:${{ secrets.GHCR_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" --follow-tags

